
version: '3.8'
services:
  db:
    image: postgres:16.0
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: my-postgres-db-pwd
    volumes:
      - postgres_data:/var/lib/postgresql/data

  identity:
    image: quay.io/keycloak/keycloak:22.0.1
    restart: unless-stopped
    ports:
      - "8180:8080"
    command:
      - start-dev
      - --import-realm
      - --db=postgres
      - --db-url=jdbc:postgresql://db:5432/keycloak
      - --db-username=keycloak
      - --db-password=my-postgres-db-pwd
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin-secret
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KEYCLOAK_LOGLEVEL: INFO
    depends_on:
      - db

volumes:
  postgres_data:
